---

configs:
  memory: "2048"
  cpus: "2"
  # if a specific ansible version has to be used, this can be changed from latest to e.g. "2.11.0"
  ansible_version: "latest"
  role_name: "ansible-role-ca"
  ip: 192.168.56.54
  domain: ca.lan
  aliases:
  - test.ca.lan
  - mail.ca.lan
  - smtp.ca.lan

...
