---
- name: Converge
  hosts: all
  vars:
    ca_domain: ca.lan
    ca_root_key_pass: ASDFJKL0e
    ca_root_cert_cn: "Root CA"
    # ca_root_validity: 3652
    ca_intermediate_cert_cn: "Intermediate CA"
    # ca_issuer_validity: 1826
    ca_cert_country: DE
    ca_cert_email: "admin@ca.lan"
    ca_cert_org: "Your Company"
    ca_cert_state: "Your State"
    ca_cert_locality: "Your City"
    ca_cert_ou: "Your OU"

    ca_certificates:
    - domain: "ca.lan"
      alt_names: []
      state: present
      validity_days: 365
    - domain: "test.ca.lan"
      alt_names: []
      state: present
      validity_days: 365
    - domain: "mail.ca.lan"
      alt_names:
      - smtp.ca.lan
      state: present
      validity_days: 365
  tasks:
  - name: "Include andrelohmann.ca"
    include_role:
      name: "andrelohmann.ca"
...
