---
- name: Converge
  hosts: all
  become: true
  become_method: ansible.builtin.sudo
  vars:
    ca_domain: ca.lan
    ca_root_key_pass: ASDFJKL0e
    ca_root_cert_cn: "Root CA"
    # ca_root_validity: 3652
    ca_cert_country: DE
    ca_cert_email: "admin@ca.lan"
    ca_cert_org: "Your Company"
    ca_cert_state: "Your State"
    ca_cert_locality: "Your City"
    ca_cert_ou: "Your OU"

    # install the ca to the system
    ca_install: true
    
    # ca_intermediate_default_validity: 1826

    ca_intermediates:
    - name: intermediate
      cn: "Intermediate CA"
      validity: 1826
      country: DE
      email: "admin@ca.lan"
      org: "Your Company"
      state: "Your State"
      locality: "Your City"
      ou: "Your OU"
    - name: intermediate2
      cn: "Intermediate CA 2"

    ca_certificates:
    - domain: "ca.lan"
      alt_names: []
      state: present
      validity_days: 365
    - domain: "test.ca.lan"
      alt_names: []
      state: present
      validity_days: 365
    - domain: "mail.ca.lan"
      alt_names:
      - smtp.ca.lan
      state: present
      validity_days: 365
  tasks:
  - name: Include andrelohmann.ca
    ansible.builtin.include_role:
      name: "andrelohmann.ca"
...
